<?php
/*======================================================================+
 File name   : botton.inc
 Begin       : 2010-08-04
 Last Update : 2013-08-25

 Description : footer and copyright

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/
?>
    <tr>
      <td style="height: 5px; width: 15%;" bgcolor="#c7c7c7"></td>
      <td style="height: 5px; width: 5px;" bgcolor="#c7c7c7"></td>
      <td style="height: 5px;" bgcolor="#c7c7c7"></td>
      <td style="height: 5px; width: 15%;" bgcolor="#c7c7c7"></td>

    </tr>
    <tr>
      <td style="height: 5px;" bgcolor="#6d931c"></td>
      <td style="height: 5px;" bgcolor="#6d931c"></td>
      <td style="height: 5px;" bgcolor="#6d931c"></td>
      <td style="height: 5px;" bgcolor="#6d931c"></td>
    </tr>
	</td>
    </tr>

  </tbody>
</table>

<small><center><font color="#a1a1a1"><i>
<blockquote>Sinx for Association Copyright (C) 2011  by Sergio Capretta

<div class="p"><!----></div>
  This program comes with ABSOLUTELY NO WARRANTY; for details type
<tt><a href="http://www.gnu.org/licenses/gpl-3.0.html">show</a></tt>.
  This is free software, and you are welcome to redistribute it
  under certain conditions; type <tt><a href="http://www.gnu.org/licenses/gpl-3.0.html">show</a></tt> for details.
</blockquote></i></center></small>
<p><center><img src='../ImmTemplate/floating_mini_sx.png'><small><i>Sinx is officially registered on <a target='_blank' href='http://savannah.nongnu.org/'>Savannah</a> as free software</i></small><img src='../ImmTemplate/floating_mini.png'></center></p>

</body>
</html>
