<?php
/*======================================================================+
 File name   : botton.inc
 Begin       : 2010-08-04
 Last Update : 2016-01-25

 Description : footer and copyright

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/
?>
    <tr>
      <td style="height: 5px; width: 15%;" bgcolor="#c7c7c7"></td>
      <td style="height: 5px; width: 5px;" bgcolor="#c7c7c7"></td>
      <td style="height: 5px;" bgcolor="#c7c7c7"></td>
      <td style="height: 5px; width: 15%;" bgcolor="#c7c7c7"></td>

    </tr>
    <tr>
      <td style="height: 5px;" bgcolor="#6d931c"></td>
      <td style="height: 5px;" bgcolor="#6d931c"></td>
      <td style="height: 5px;" bgcolor="#6d931c"></td>
      <td style="height: 5px;" bgcolor="#6d931c"></td>
    </tr>
	</td>
    </tr>

  </tbody>
</table>

<!-- Tasti scelta rapida -->
<center>
    <a href="./pre_stampa_soci.php"><img src="./ImmTemplate/Pulsanti/LibroSoci.png"></a>
    <a href="./Rubrica.php"><img src="./ImmTemplate/Pulsanti/Rubrica.png"></a>
    <a href="./Manuale.php"><img src="./ImmTemplate/Pulsanti/Manuale2.png"></a>
    <a href="./InsPrimanota.php"><img src="./ImmTemplate/Pulsanti/PrimaNota.png"></a>
    <a href="./InsRicFisc.php"><img src="./ImmTemplate/Pulsanti/Ricevuta.png"></a>
    <a href="./InsFattura.php"><img src="./ImmTemplate/Pulsanti/Fattura.png"></a>
    <a href="./Calendario2.php"><img src="./ImmTemplate/Pulsanti/Calendario.png"></a>
    <a href="./Rip_database.php"><img src="./ImmTemplate/Pulsanti/Backup.png"></a>
</center>

<!-- Copyright -->
<small><center><font color="#a1a1a1"><i>
<blockquote>Sinx for Association Copyright (C) 2011-2016  by Sergio Capretta

<div class="p"><!----></div>
  This program comes with ABSOLUTELY NO WARRANTY; for details type
<tt><a target='_blank' href="http://www.gnu.org/licenses/gpl-3.0.html">show</a></tt>.
  This is free software, and you are welcome to redistribute it
  under certain conditions; type <tt><a target='_blank' href="http://www.gnu.org/licenses/gpl-3.0.html">show</a></tt> for details.
</blockquote></i></center></small>

<!-- Savannah -->
<p><center><img src='./ImmTemplate/floating_mini_sx.png'><small><i>Sinx is officially registered on <a target='_blank' href='http://savannah.nongnu.org/'>Savannah</a> as free software</i></small><img src='./ImmTemplate/floating_mini.png'></center></p>

<!-- Pulsante fsf member -->
<center><a href="http://www.fsf.org/register_form?referrer=12556"><img src="http://static.fsf.org/nosvn/associate/fsf-12556.png" alt="[FSF Associate Member]" /></a></center>
</body>
</html>
