<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//Menu
$Lassociazione = "Associazione";
$Lsito = " Sito Web";
$Ldatiassociazione = " Dati Associazione";
$Lanagrafica = "Anagrafica";
$Lfondatori = " Fondatori";
$Lassociati = " Associati";
$Laltri = " Altri";
$Lcerca = " Cerca";
$Lrubrica = " Rubrica";
$Llibrosoci = " Libro Soci";


//top
$Lpresentazione = "Gestionale per Associazioni senza scopo di lucro";
$Lutente = "Utente: ";
$Llivello = "Livello: ";
$Lora = "Ora: ";
$Ldata = "Data: ";
$Lversione = "Versione: ";

//index2
$Lbenvenuto = "Benvenuto";
$Lfrase = "Benvenuti in Sinx: sofware gestionale pensato per Associazioni No-Profit.<br>
Sinx &egrave liberamente disponibile sotto <a href='./Licenza.php'>licenza GPLv3 (GNU General Public License)</a><br>
<a href='./Licenza_eng.php'>Versione ufficiale licenza GPLv3</a><br><br>
Questo software NON HA ALCUNA GARANZIA.<br><br>
Se hai dei suggerimenti o vuoi partecipare pi&ugrave o meno attivamente allo sviluppo del software, se vuoi dare un contributo o essere aggiornato con tutte le novit&agrave di Sinx, consulta il sito <a href='http://www.sinx.it'>http://www.sinx.it</a> oppure manda una mail a <a href='mailto:info@sinx.it'>info@sinx.it</a>.<br><br>
<center><img style='border: 0px; width: 30px; height: 30px;' src='./ImmTemplate/logoFirefox.jpg'><br><small><b>Ottimizzato per Mozilla Firefox</b></small>
<p><center>Per amministrare il sistema, fare clic su uno dei link nel menu alla sinistra dello schermo.<br>Se non lo hai gi&agrave fatto, <b>leggi bene il manuale d'uso di Sinx</b>, lo trovi anche nel men&ugrave</p>";
$Lptitolonote = "Blocco Note";
$Ldescrizionenote = "<a href='./InsNotepad.php'>Da qui</a> o da men&ugrave (Gestione -> Blocco Note), puoi gestire le note";

//help
$Lhelpindex2 = "<hr><img src='./Immagini/suggerimento.png'><small><i>Le prime quattro lettere del men&ugrave indicano all'utente i permessi di accesso alle pagine:<br>A - amministratore<br>o - operatore<br>l - limitato<br>a - associato<br><br>x - Non pu&ograve entrare<br>- - pu&ograve entrare ma non modificare<br><hr></i></small>";
?>
